[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
	knolleary/PubSubClient@^2.8
	nkolban/ESP32 BLE Arduino@^1.0.1
	prampec/IotWebConf@^3.2.1

build_flags =
	-DWIFI_POWER_2dBm
